services:
  - type: web
    name: minibot-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: ./start.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: OPENAI_API_KEY
        sync: false
      - key: PINECONE_API_KEY  
        sync: false
      - key: OPENAI_CHAT_MODEL
        value: gpt-4o-mini
      - key: OPENAI_EMBED_MODEL
        value: text-embedding-3-small
      - key: PINECONE_INDEX_KB
        value: kb-openai-1536
      - key: KB_MATCH_THRESHOLD
        value: "0.7" 